apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysqldb
    app: test-v2
  name: mysqldb
spec:
  containers:
  - name: mysqldb
    image: mysql
    env:
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "yes"
    ports:
    - containerPort: 3306
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1Gi
